---
- name: fix permissions
  become: yes
  file:
    path: "{{ application.directory }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: directory
    recurse: yes
  listen: fix permissions

- name: reload systemd
  become: yes
  command: systemctl daemon-reload
  listen: reload systemd
